import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

import Background from '@/components/Background/Background';
import 'modern-normalize/modern-normalize.css';

import './globals.css';
import * as styles from './layout.css';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <main className={styles.page}>
          <Background />
          <div className={styles.content}>{children}</div>
        </main>
      </body>
    </html>
  );
}
