import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

import { NuqsAdapter } from 'nuqs/adapters/next';
import 'modern-normalize/modern-normalize.css';

import Background from '@/components/Background/Background';

import './globals.css';
import * as styles from './layout.css';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Greenfield project',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <NuqsAdapter>
          <main className={styles.page}>
            <Background />
            <div className={styles.content}>{children}</div>
          </main>
        </NuqsAdapter>
      </body>
    </html>
  );
}
